# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcb0b4b5b24ecde8364be4b3f13d3f0cde661d739b7679a63c052490ecef0b3b958331976122a6ff9cb887a5c28373b60f81bf832dac1bffc08913fc2d162d07

test:
  secret_key_base: 677dde8f6ef4e1745e7a3019d56ed842a7f52aa031ada54a0692aa0ce87f407691bffecdd4be977c51cd5322aa08a6a356ff2f50524615fbc61fbab956730a07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
